spring.datasource.url=jdbc:postgresql://localhost:5432/ngo_saeca
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.banner-mode=off

# Configuración de logs para mantener la terminal limpia y mostrar solo errores críticos
logging.level.root=WARN
logging.level.org.hibernate=ERROR
logging.level.org.springframework.web=ERROR
org.springframework.boot=ERROR