-- Esquema para H2 (equivale al de PostgreSQL de db/ngo_ans.sql). Es idempotente: se puede ejecutar en cada arranque.

CREATE TABLE IF NOT EXISTS rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    clave VARCHAR(255) NOT NULL,
    estado VARCHAR(30) DEFAULT 'ACTIVO',
    CONSTRAINT usuario_correo_key UNIQUE (correo),
    CONSTRAINT usuario_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);

CREATE TABLE IF NOT EXISTS cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    documento VARCHAR(20) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    correo VARCHAR(100),
    CONSTRAINT cliente_documento_unique UNIQUE (documento),
    CONSTRAINT cliente_documento_check CHECK (REGEXP_LIKE(documento, '^[0-9]+$')),
    CONSTRAINT cliente_telefono_check CHECK (REGEXP_LIKE(telefono, '^\+?[0-9]+$'))
);

CREATE TABLE IF NOT EXISTS articulo (
    id_articulo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    categoria VARCHAR(50),
    precio NUMERIC(10,2) NOT NULL,
    stock INTEGER DEFAULT 0 NOT NULL,
    estado VARCHAR(30) DEFAULT 'ACTIVO' NOT NULL,
    marca VARCHAR(50),
    modelo VARCHAR(50),
    CONSTRAINT articulo_precio_check CHECK (precio >= 0),
    CONSTRAINT articulo_stock_check CHECK (stock >= 0)
);

CREATE TABLE IF NOT EXISTS venta (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vendedor BIGINT NOT NULL,
    id_cliente BIGINT,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(12,2) DEFAULT 0 NOT NULL,
    CONSTRAINT venta_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT venta_id_vendedor_fkey FOREIGN KEY (id_vendedor) REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS detalle_venta (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta BIGINT NOT NULL,
    id_articulo BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,
    CONSTRAINT detalle_venta_cantidad_check CHECK (cantidad > 0),
    CONSTRAINT detalle_venta_id_articulo_fkey FOREIGN KEY (id_articulo) REFERENCES articulo(id_articulo),
    CONSTRAINT detalle_venta_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES venta(id_venta) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    nro_serie VARCHAR(50) NOT NULL,
    tipo_producto VARCHAR(50) NOT NULL,
    id_cliente BIGINT NOT NULL,
    fecha_venta DATE NOT NULL,
    id_venta BIGINT,
    CONSTRAINT producto_nro_serie_key UNIQUE (nro_serie),
    CONSTRAINT producto_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT producto_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES venta(id_venta)
);

CREATE TABLE IF NOT EXISTS solicitud (
    id_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    descripcion VARCHAR(100000) NOT NULL,
    estado_actual VARCHAR(30) DEFAULT 'RECIBIDA' NOT NULL,
    codigo_publico VARCHAR(40),
    numero_solicitud VARCHAR(20) NOT NULL,
    CONSTRAINT solicitud_codigo_publico_key UNIQUE (codigo_publico),
    CONSTRAINT solicitud_numero_solicitud_key UNIQUE (numero_solicitud),
    CONSTRAINT solicitud_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT solicitud_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE TABLE IF NOT EXISTS asignacion (
    id_asignacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT asignacion_id_solicitud_fkey FOREIGN KEY (id_solicitud) REFERENCES solicitud(id_solicitud),
    CONSTRAINT asignacion_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS seguimiento (
    id_seguimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(30) NOT NULL,
    diagnostico VARCHAR(100000),
    CONSTRAINT seguimiento_id_solicitud_fkey FOREIGN KEY (id_solicitud) REFERENCES solicitud(id_solicitud),
    CONSTRAINT seguimiento_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS reclamo (
    id_reclamo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud BIGINT NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    mensaje VARCHAR(500),
    CONSTRAINT reclamo_id_solicitud_fkey FOREIGN KEY (id_solicitud) REFERENCES solicitud(id_solicitud)
);
